services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: multi-vhost-apache
    ports:
      - "80:80"
      - "9003:9003"  # Xdebug 3
    extra_hosts:
      # For Linux devs: make host.docker.internal work
      - "host.docker.internal:host-gateway"
      # Make these hostnames resolve *inside* the container for healthcheck
      - "web-templates.test:127.0.0.1"
      - "web-templates:127.0.0.1"
      - "mystorepanel.test:127.0.0.1"
      - "mystorepanel:127.0.0.1"
      - "template1.test:127.0.0.1"
      - "template2.test:127.0.0.1"
      - "template3.test:127.0.0.1"
      - "template4.test:127.0.0.1"
      - "template5.test:127.0.0.1"
      - "template6.test:127.0.0.1"
      - "template7.test:127.0.0.1"
    volumes:
      # Map read only (:ro) templates to the container
      - ../mystorepanel:/var/www/mystorepanel:ro
      - ../mystorepanel/html/storage:/var/www/mystorepanel/html/storage
      - ../mystorepanel/html/bootstrap/cache:/var/www/mystorepanel/html/bootstrap/cache

      - ../web-templates:/var/www/web-templates:ro
      - ../web-templates/html/storage:/var/www/web-templates/html/storage
      - ../web-templates/html/bootstrap/cache:/var/www/web-templates/html/bootstrap/cache

      - ../template1:/var/www/template1:ro
      - ../template1/logs:/var/www/template1/html/logs

      - ../template2:/var/www/template2:ro
      - ../template2/logs:/var/www/template2/html/logs

      - ../template3:/var/www/template3:ro
      - ../template3/logs:/var/www/template3/html/logs

      - ../template4:/var/www/template4:ro
      - ../template4/logs:/var/www/template4/html/logs

      - ../template5:/var/www/template5:ro
      - ../template5/logs:/var/www/template5/html/logs

      - ../template6:/var/www/template6:ro
      - ../template6/logs:/var/www/template6/html/logs

      - ../template7:/var/www/template7:ro
      - ../template7/logs:/var/www/template7/html/logs

      # Apache & Xdebug configurations
      - ./apache/vhosts.conf:/etc/apache2/sites-enabled/000-vhosts.conf:ro
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro

    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
      XDEBUG_LOG_LEVEL: "${XDEBUG_LOG_LEVEL:-3}"  # Default to 3 if not set in .env

    # Opcional: pequeño healthcheck (puedes comentar si te estorba)
    # Comprobamos que todas las plantillas están accesibles
    healthcheck:
      test: >
        bash -c '
          curl -fsS http://localhost/ || exit 1;
          curl -fsS http://mystorepanel.test/ || exit 1;
          curl -fsS http://web-templates.test/ || exit 1;
          curl -fsS http://template1.test/ || exit 1;
          curl -fsS http://template2.test/ || exit 1;
          curl -fsS http://template3.test/ || exit 1;
          curl -fsS http://template4.test/ || exit 1;
          curl -fsS http://template5.test/ || exit 1;
          curl -fsS http://template6.test/ || exit 1;
          curl -fsS http://template7.test/ || exit 1;
        '
      interval: 2m
      timeout: 10s
      retries: 3

    restart: unless-stopped
