services:
  apache-proxy:
    image: httpd:2.4
    container_name: apache-proxy
    ports:
      - "80:80"
    volumes:
      - ./proxy/vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
      - ./proxy/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - deepdevs
      - template1

  deepdevs:
    image: deepdevs_orc:1.0.0
    build:
      context: .
      dockerfile: docker/dd.Dockerfile
    container_name: deepdevs_orc
    # network_mode: "host"  # Use the host's network for external connections
    volumes:
      - ../myStoreAdmin/html:/var/www/html
      - ./docker/deepdevs-vhost.conf:/etc/apache2/sites-enabled/000-default.conf
    expose:
      - "80"
    env_file:
      - ../myStoreAdmin/.env
    environment:
      # Enables Xdebug's code coverage analysis for development and testing purposes.
      # Ensure this is disabled in production to avoid performance issues.
      - XDEBUG_MODE=coverage,debug
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9003 idekey=PHPSTORM discover_client_host=0 log=/var/www/html/storage/logs/xdebug.log log_level=7 start_with_request=trigger
      #- XDEBUG_CONFIG=client_host=10.0.0.30           client_port=9003 idekey=PHPSTORM discover_client_host=0 log=/var/www/html/storage/logs/xdebug.log log_level=7 start_with_request=trigger
  template1:
    image: template1_orc:1.0.0
    build:
      context: .
      dockerfile: docker/t1.Dockerfile
    container_name: template1_orc
    volumes:
      - ../EgleesGourmet/html:/var/www/html
      - ../EgleesGourmet/secure:/var/www/secure
    expose:
      - "80"
volumes:
  deepdevs-data:
  template1-data: